#!/usr/bin/env python3
"""
deploy.py — VS AgentCore Multi-Agent Deployment
================================================
Cross-platform replacement for deploy.sh (Windows / Mac / Linux).

Usage:
    python deploy.py check
    python deploy.py prompts
    python deploy.py secrets
    python deploy.py iam
    python deploy.py guardrails
    python deploy.py lambdas
    python deploy.py gateway
    python deploy.py platform
    python deploy.py agents
    python deploy.py ssm-arns
    python deploy.py registry
    python deploy.py redeploy [platform|ui|both]
    python deploy.py all

Requirements:
    pip install boto3
    aws-cli, docker, terraform must be on PATH
"""

import json
import re
import os
import subprocess
import sys
import time
from datetime import datetime
from pathlib import Path

import boto3
from botocore.exceptions import ClientError

# ── Config ────────────────────────────────────────────────────────────────

REGION       = os.environ.get("AWS_REGION", "us-east-1")
PREFIX       = "vs-agentcore-ma"
SSM_PREFIX   = "/vs-agentcore-multiagent/prod"
GATEWAY_NAME = "vs-agentcore-ma-mcp"
ROOT         = Path(__file__).resolve().parent.parent  # deploy.py lives in scripts/ — root is one level up

AGENTS     = ["research", "knowledge", "safety", "chart", "supervisor"]
SUB_AGENTS = ["research", "knowledge", "safety", "chart"]

# ── Console helpers ───────────────────────────────────────────────────────

def ok(msg):    print(f"  \u2705 {msg}")
def fail(msg):  print(f"  \u274c {msg}")
def warn(msg):  print(f"  \u26a0\ufe0f  {msg}")
def info(msg):  print(f"  {msg}")
def header(msg):print(f"\n\u25ba {msg}")
def sep():      print("  " + "\u2550" * 50)

_PASS = _FAIL = 0

def chk_ok(msg):
    global _PASS; _PASS += 1; ok(msg)

def chk_fail(msg):
    global _FAIL; _FAIL += 1; fail(msg)

def chk_warn(msg):
    warn(msg)

# ── Resource tracking ─────────────────────────────────────────────────────

_RES_FILE = ROOT / "deployed_resources.txt"

def _init_res():
    if not _RES_FILE.exists():
        _RES_FILE.write_text(
            "# VS AgentCore Multi-Agent — Deployed Resources\n"
            "# Generated by deploy.py\n"
            "# Format: timestamp  [category]  name  value\n\n"
        )

def track(category, name, value):
    _init_res()
    ts   = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    line = f"{ts}  [{category:<20}]  {name:<30}  {value}\n"
    with open(_RES_FILE, "a") as f:
        f.write(line)

# ── Subprocess ────────────────────────────────────────────────────────────

def run(cmd, cwd=None, check=True, capture=False, stdin_text=None, extra_env=None):
    """Run a subprocess. Returns CompletedProcess."""
    env = {**os.environ, **(extra_env or {})}
    result = subprocess.run(
        [str(c) for c in cmd],
        cwd            = str(cwd or ROOT),
        capture_output = capture,
        text           = True,
        input          = stdin_text,
        env            = env,
    )
    if check and result.returncode != 0:
        err = (result.stderr or result.stdout or "")[:400]
        raise RuntimeError(f"Command failed ({result.returncode}): {' '.join(str(c) for c in cmd)}\n{err}")
    return result

def run_or_warn(label, cmd, cwd=None):
    """Run a command; skip silently on 'already exists' errors."""
    r = run(cmd, cwd=cwd, check=False, capture=True)
    if r.returncode == 0:
        ok(label)
        return True
    output = (r.stdout or "") + (r.stderr or "")
    if any(x in output.lower() for x in [
        "already exist", "alreadyexists", "resourceexistsexception",
        "entityalreadyexists", "namealreadyexistsexception",
    ]):
        info(f"{label} — already exists, skipping")
        return True
    warn(f"{label} — failed: {output[:120]}")
    return False

# ── AWS client factory ────────────────────────────────────────────────────

def c(service):
    return boto3.client(service, region_name=REGION)

def get_account_id():
    return c("sts").get_caller_identity()["Account"]

# ── ECR helpers ───────────────────────────────────────────────────────────

def ecr_login(account_id):
    ecr_base = f"{account_id}.dkr.ecr.{REGION}.amazonaws.com"
    pwd = run(["aws", "ecr", "get-login-password", "--region", REGION], capture=True).stdout.strip()
    run(["docker", "login", "--username", "AWS", "--password-stdin", ecr_base], stdin_text=pwd)
    info(f"ECR login: {ecr_base}")
    return ecr_base

def ensure_ecr_repo(account_id, name):
    full = f"{PREFIX}/{name}"
    try:
        c("ecr").describe_repositories(repositoryNames=[full])
    except ClientError as e:
        if "RepositoryNotFoundException" in str(e):
            c("ecr").create_repository(repositoryName=full)
    return f"{account_id}.dkr.ecr.{REGION}.amazonaws.com/{full}"

# ── Wait helpers ──────────────────────────────────────────────────────────

def wait_lambda(name, retries=30, delay=3):
    print(f"  Waiting for {name}", end="", flush=True)
    for _ in range(retries):
        try:
            s = c("lambda").get_function(FunctionName=name)["Configuration"]["State"]
            if s == "Active":
                print(" \u2705")
                return True
        except ClientError:
            pass
        print(".", end="", flush=True)
        time.sleep(delay)
    print(" \u26a0\ufe0f  timeout")
    return False

def wait_runtime(runtime_id, retries=60, delay=5):
    print("  Waiting for READY", end="", flush=True)
    agc = c("bedrock-agentcore-control")
    for _ in range(retries):
        try:
            s = agc.get_agent_runtime(agentRuntimeId=runtime_id)["status"]
            if s == "READY":
                print(" \u2705")
                return True
        except ClientError:
            pass
        print(".", end="", flush=True)
        time.sleep(delay)
    print(" \u26a0\ufe0f  timeout — check AWS Console")
    return False

# ── Prerequisites check ───────────────────────────────────────────────────

def check_prereqs():
    import shutil
    missing = []
    for tool in ["aws", "docker", "terraform", "python3"]:
        if not shutil.which(tool) and not shutil.which(tool + ".exe"):
            missing.append(tool)
    if missing:
        print(f"\u274c Missing tools on PATH: {', '.join(missing)}")
        sys.exit(1)
    try:
        c("sts").get_caller_identity()
    except Exception:
        print("\u274c AWS credentials not configured. Run: aws configure")
        sys.exit(1)

# ─────────────────────────────────────────────────────────────────────────
# STEPS
# ─────────────────────────────────────────────────────────────────────────

def step_check():
    global _PASS, _FAIL
    _PASS = _FAIL = 0
    header("Check: Verifying prerequisites and existing AWS resources")

    sm  = c("secretsmanager")
    ssm = c("ssm")

    # Secrets
    print("\n  \u2500\u2500 Secrets Manager")
    for secret in ["openai", "pinecone", "neo4j", "postgres", "platform_api_key"]:
        try:
            sm.get_secret_value(SecretId=f"{SSM_PREFIX}/{secret}")
            chk_ok(f"{SSM_PREFIX}/{secret}")
        except ClientError:
            chk_fail(f"{SSM_PREFIX}/{secret}  \u2192  run: python deploy.py secrets")

    # Bedrock Prompts
    print("\n  \u2500\u2500 Bedrock Prompts")
    for agent in ["supervisor", "research", "knowledge", "safety", "chart"]:
        try:
            pid  = ssm.get_parameter(Name=f"/{agent}-agent/prod/bedrock/prompt_id")["Parameter"]["Value"]
            pver = ssm.get_parameter(Name=f"/{agent}-agent/prod/bedrock/prompt_version")["Parameter"]["Value"]
            chk_ok(f"{agent}-agent  prompt_id={pid}  version={pver}")
        except ClientError:
            chk_fail(f"{agent}-agent prompt missing  \u2192  run: python deploy.py prompts")

    # MCP Gateway
    print("\n  \u2500\u2500 MCP Gateway")
    try:
        url = ssm.get_parameter(Name=f"{SSM_PREFIX}/mcp/gateway_url")["Parameter"]["Value"]
        chk_ok(f"Gateway URL: {url}")
    except ClientError:
        try:
            old = ssm.get_parameter(Name="/vs-agentcore/prod/mcp/gateway_url")["Parameter"]["Value"]
            chk_warn("Found single-agent gateway — copying to new SSM prefix...")
            ssm.put_parameter(Name=f"{SSM_PREFIX}/mcp/gateway_url", Value=old, Type="String", Overwrite=True)
            chk_ok(f"Gateway URL copied: {old}")
        except ClientError:
            chk_fail("MCP Gateway missing  \u2192  run: python deploy.py gateway")

    # Lambda tools
    print("\n  \u2500\u2500 Lambda Tools")
    for tool in ["search", "graph", "hitl", "summariser", "chart"]:
        func = f"{PREFIX}-{tool}-tool"
        try:
            s = c("lambda").get_function(FunctionName=func)["Configuration"]["State"]
            chk_ok(func) if s == "Active" else chk_fail(f"{func} state={s}")
        except ClientError:
            chk_fail(f"{func} missing  \u2192  run: python deploy.py lambdas")

    # RDS
    print("\n  \u2500\u2500 RDS Postgres")
    try:
        inst = c("rds").describe_db_instances()["DBInstances"][0]
        s    = inst["DBInstanceStatus"]
        if s == "available":
            chk_ok(f"RDS: {inst['Endpoint']['Address']}")
        else:
            chk_fail(f"RDS status={s}  \u2192  run: python deploy.py platform")
    except Exception:
        chk_fail("RDS not found  \u2192  run: python deploy.py platform")

    # Bedrock Guardrail
    print("\n  \u2500\u2500 Bedrock Guardrail")
    try:
        gid  = ssm.get_parameter(Name=f"{SSM_PREFIX}/bedrock/guardrail_id")["Parameter"]["Value"]
        gver = ssm.get_parameter(Name=f"{SSM_PREFIX}/bedrock/guardrail_version")["Parameter"]["Value"]
        chk_ok(f"guardrail_id={gid}  version={gver}")
    except ClientError:
        chk_fail("Guardrail missing  \u2192  run: python deploy.py guardrails")

    # DynamoDB
    print("\n  \u2500\u2500 DynamoDB")
    try:
        tbl = ssm.get_parameter(Name=f"{SSM_PREFIX}/dynamodb/trace_table_name")["Parameter"]["Value"]
        try:
            s = c("dynamodb").describe_table(TableName=tbl)["Table"]["TableStatus"]
            chk_ok(f"Table {tbl} ({s})") if s == "ACTIVE" else chk_warn(f"Table {tbl} status={s}")
        except ClientError:
            chk_warn(f"Table {tbl} in SSM but not in DynamoDB — agent will create it")
    except ClientError:
        chk_fail("DynamoDB SSM param missing  \u2192  run: python deploy.py secrets")

    # IAM
    print("\n  \u2500\u2500 IAM Roles")
    iam = c("iam")
    for role in ["lambda-mcp", "gateway-role", "agent-role"]:
        try:
            iam.get_role(RoleName=f"{PREFIX}-{role}")
            chk_ok(f"{PREFIX}-{role}")
        except ClientError:
            chk_fail(f"{PREFIX}-{role} missing  \u2192  run: python deploy.py iam")

    # AgentCore Runtime ARNs
    print("\n  \u2500\u2500 AgentCore Runtime ARNs")
    for agent in AGENTS:
        try:
            arn = ssm.get_parameter(Name=f"{SSM_PREFIX}/agents/{agent}/runtime_arn")["Parameter"]["Value"]
            chk_ok(f"{agent}: {arn[:70]}...")
        except ClientError:
            chk_warn(f"{agent}: not deployed yet")

    print()
    sep()
    print(f"  Check complete: {_PASS} passed  {_FAIL} failed")
    if _FAIL == 0:
        ok("All prerequisites met — ready to deploy")
    else:
        fail(f"Fix {_FAIL} failed check(s) above before deploying")
    sep()


def step_prompts():
    header("Step 0: Bedrock Prompts")

    prompts_dir = ROOT / "prompts"
    if not prompts_dir.exists():
        fail(f"prompts/ directory not found at {prompts_dir}")
        sys.exit(1)

    bedrock = c("bedrock-agent")
    ssm     = c("ssm")

    agents = ["supervisor", "research", "knowledge", "safety", "chart"]

    for agent in agents:
        pfile = prompts_dir / f"{agent}.txt"
        if not pfile.exists():
            info(f"Skipping {agent} — {pfile.name} not found")
            continue

        prompt_text = pfile.read_text(encoding="utf-8")
        app_name    = f"{agent}-agent"
        ssm_id_key  = f"/{app_name}/prod/bedrock/prompt_id"
        ssm_ver_key = f"/{app_name}/prod/bedrock/prompt_version"

        # Step 1 — resolve existing prompt ID from SSM
        existing_id = None
        try:
            v = ssm.get_parameter(Name=ssm_id_key)["Parameter"]["Value"]
            if v and v != "CHANGE_ME":
                existing_id = v
                info(f"[{agent}] Found in SSM: {existing_id}")
        except ClientError:
            pass

        # Step 2 — if SSM miss, try to create in Bedrock.
        # If Bedrock says the name already exists, extract the ID from the
        # error message (same pattern as single-agent deploy.sh) and write
        # it to SSM immediately so the next run finds it in step 1.
        if not existing_id:
            info(f"[{agent}] Creating new Bedrock prompt...")
            try:
                resp      = bedrock.create_prompt(
                    name        = f"vs-agentcore-ma-{agent}",
                    description = f"{agent.capitalize()} Agent system prompt",
                    variants    = [{
                        "name":         "default",
                        "modelId":      "anthropic.claude-3-5-sonnet-20241022-v2:0",
                        "templateType": "TEXT",
                        "templateConfiguration": {"text": {"text": prompt_text, "inputVariables": []}},
                        "inferenceConfiguration": {"text": {"temperature": 0.0, "maxTokens": 4096}},
                    }],
                    defaultVariant = "default",
                )
                existing_id = resp["id"]
                info(f"[{agent}] Created: {existing_id}")
            except ClientError as e:
                # ConflictException carries the existing ID in its message:
                # "...already exists for id GLMV90RUMZ..."
                m = re.search(r"already exists for id ([A-Z0-9]+)", str(e))
                if m:
                    existing_id = m.group(1)
                    info(f"[{agent}] Already exists in Bedrock ({existing_id}) — versioning...")
                    # Write to SSM now so next run finds it in step 1
                    ssm.put_parameter(Name=ssm_id_key, Value=existing_id,
                                      Type="String", Overwrite=True)
                else:
                    fail(f"[{agent}] Create failed: {e}")
                    continue

        # Step 3 — push updated content from .txt file into Bedrock draft,
        # then stamp a new version. This ensures the .txt file is the source
        # of truth — every deploy picks up whatever is in prompts/{agent}.txt.
        try:
            bedrock.update_prompt(
                promptIdentifier = existing_id,
                name             = f"vs-agentcore-ma-{agent}",   # required by API
                description      = f"{agent.capitalize()} Agent system prompt",
                variants         = [{
                    "name":         "default",
                    "modelId":      "anthropic.claude-3-5-sonnet-20241022-v2:0",
                    "templateType": "TEXT",
                    "templateConfiguration": {
                        "text": {"text": prompt_text, "inputVariables": []}
                    },
                    "inferenceConfiguration": {
                        "text": {"temperature": 0.0, "maxTokens": 4096}
                    },
                }],
                defaultVariant = "default",
            )
            info(f"[{agent}] Content updated from prompts/{agent}.txt")
            v_resp        = bedrock.create_prompt_version(
                promptIdentifier = existing_id,
                description      = f"deploy.py — {app_name}",
            )
            prompt_id     = existing_id
            prompt_version = str(v_resp["version"])
        except Exception as e:
            fail(f"[{agent}] update/version failed: {e}")
            continue

        ssm.put_parameter(Name=ssm_id_key,  Value=prompt_id,      Type="String", Overwrite=True)
        ssm.put_parameter(Name=ssm_ver_key, Value=prompt_version, Type="String", Overwrite=True)
        ok(f"[{agent}]  prompt_id={prompt_id}  version={prompt_version}")

        try:
            track("bedrock-prompt", app_name, prompt_id)
        except Exception:
            pass

    ok("Prompts done")


def step_secrets():
    header("Step 1: Secrets + SSM")

    required = ["OPENAI_API_KEY", "PINECONE_API_KEY", "NEO4J_URI",
                "NEO4J_USER", "NEO4J_PASSWORD", "PLATFORM_API_KEY",
                "LANGSMITH_API_KEY"]
    missing  = [k for k in required if not os.environ.get(k)]
    if missing:
        fail(f"Missing env vars: {missing}")
        fail("Run: source .env.prod  (Linux/Mac)  or  .env.prod.bat  (Windows)")
        sys.exit(1)

    sm  = c("secretsmanager")
    ssm = c("ssm")

    def put_secret(name, value):
        try:
            sm.create_secret(Name=name, SecretString=json.dumps(value))
            ok(f"Created secret: {name}")
        except ClientError as e:
            if "ResourceExistsException" in str(e):
                sm.update_secret(SecretId=name, SecretString=json.dumps(value))
                ok(f"Updated secret: {name}")
            else:
                raise

    def put_param(name, value, secure=False):
        ssm.put_parameter(Name=name, Value=value,
                          Type="SecureString" if secure else "String", Overwrite=True)
        ok(f"SSM param: {name}")

    put_secret(f"{SSM_PREFIX}/openai",           {"api_key": os.environ["OPENAI_API_KEY"]})
    put_secret(f"{SSM_PREFIX}/pinecone",         {"api_key": os.environ["PINECONE_API_KEY"]})
    put_secret(f"{SSM_PREFIX}/neo4j",            {"uri": os.environ["NEO4J_URI"],
                                                   "user": os.environ["NEO4J_USER"],
                                                   "password": os.environ["NEO4J_PASSWORD"]})
    put_secret(f"{SSM_PREFIX}/platform_api_key", {"api_key": os.environ["PLATFORM_API_KEY"]})

    # LangSmith observability
    put_secret(f"{SSM_PREFIX}/langsmith", {
        "api_key": os.environ["LANGSMITH_API_KEY"],
        "project": os.environ.get("LANGSMITH_PROJECT", "langchain-agent-experiments"),
        "tracing": os.environ.get("LANGSMITH_TRACING", "true"),
    })
    ok("LangSmith secret written")

    # Write platform_api_key to BOTH SSM paths:
    # 1. New prefix — used by agents and platform middleware
    # 2. Old prefix (/vs-agentcore/prod/) — used by Terraform main.tf secrets injection
    #    for the ECS UI task (AGENT_API_KEY env var). Without this the UI task fails with
    #    "invalid ssm parameters" and the UI sends no X-API-Key → 401 from platform.
    put_param(f"{SSM_PREFIX}/platform_api_key",       os.environ["PLATFORM_API_KEY"], secure=True)
    put_param("/vs-agentcore/prod/platform_api_key",  os.environ["PLATFORM_API_KEY"], secure=True)

    postgres_url = os.environ.get("POSTGRES_URL", "")
    if postgres_url and "<rds-endpoint>" not in postgres_url:
        from urllib.parse import urlparse
        pg = urlparse(postgres_url)
        put_secret(f"{SSM_PREFIX}/postgres", {
            "username": pg.username, "password": pg.password,
            "host":     pg.hostname, "port": str(pg.port or 5432),
            "dbname":   pg.path.lstrip("/"),
        })
    else:
        warn("Skipping postgres — set POSTGRES_URL after step_platform then re-run secrets")

    put_param("/clinical-agent/prod/pinecone/api_key",     os.environ["PINECONE_API_KEY"], secure=True)
    put_param("/clinical-agent/prod/pinecone/index_name",  os.environ.get("PINECONE_INDEX_NAME", "clinical-agent"))
    put_param(f"{SSM_PREFIX}/pinecone/clinical_trials_index", os.environ.get("CLINICAL_TRIALS_INDEX", "clinical-trials-index"))
    put_param(f"{SSM_PREFIX}/dynamodb/trace_table_name",   f"{PREFIX}-traces")
    put_param("/clinical-agent/prod/dynamodb/trace_table_name", f"{PREFIX}-traces")

    ok("Secrets done")


def step_iam():
    header("Step 2: IAM Roles")
    iam = c("iam")
    account_id = get_account_id()

    def create_role(name, trust_doc):
        run_or_warn(f"Create {name}", [
            "aws", "iam", "create-role",
            "--role-name", name,
            "--assume-role-policy-document", json.dumps(trust_doc),
        ])

    def put_policy(role_name, policy_name, policy_doc):
        try:
            iam.put_role_policy(RoleName=role_name, PolicyName=policy_name,
                                PolicyDocument=json.dumps(policy_doc))
            ok(f"{role_name} policy updated")
        except ClientError as e:
            warn(f"{role_name} policy update failed: {e}")

    lambda_trust = {"Version": "2012-10-17", "Statement": [{"Effect": "Allow",
        "Principal": {"Service": "lambda.amazonaws.com"}, "Action": "sts:AssumeRole"}]}

    create_role(f"{PREFIX}-lambda-mcp", lambda_trust)
    run_or_warn(f"Attach AWSLambdaBasicExecutionRole to {PREFIX}-lambda-mcp", [
        "aws", "iam", "attach-role-policy",
        "--role-name", f"{PREFIX}-lambda-mcp",
        "--policy-arn", "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole",
    ])
    put_policy(f"{PREFIX}-lambda-mcp", "SecretsAccess", {
        "Version": "2012-10-17",
        "Statement": [
            {"Sid": "SecretsAndConfig", "Effect": "Allow",
             "Action": ["secretsmanager:GetSecretValue", "ssm:GetParameter",
                        "ssm:GetParameters", "kms:Decrypt"], "Resource": "*"},
            {"Sid": "CloudWatchLogs", "Effect": "Allow",
             "Action": ["logs:CreateLogGroup", "logs:CreateLogStream", "logs:PutLogEvents",
                        "logs:DescribeLogGroups", "logs:DescribeLogStreams"], "Resource": "*"},
        ]
    })

    gw_trust = {"Version": "2012-10-17", "Statement": [{"Sid": "GatewayAssumeRolePolicy",
        "Effect": "Allow", "Principal": {"Service": "bedrock-agentcore.amazonaws.com"},
        "Action": "sts:AssumeRole"}]}
    create_role(f"{PREFIX}-gateway-role", gw_trust)
    put_policy(f"{PREFIX}-gateway-role", "GatewayPolicy", {
        "Version": "2012-10-17",
        "Statement": [
            {"Sid": "InvokeLambdaTools", "Effect": "Allow",
             "Action": ["lambda:InvokeFunction"],
             "Resource": [f"arn:aws:lambda:{REGION}:{account_id}:function:{PREFIX}-{t}-tool"
                          for t in ["search", "graph", "hitl", "summariser", "chart"]]},
            {"Sid": "CloudWatchLogs", "Effect": "Allow",
             "Action": ["logs:CreateLogGroup", "logs:CreateLogStream", "logs:PutLogEvents",
                        "logs:DescribeLogGroups", "logs:DescribeLogStreams"], "Resource": "*"},
        ]
    })

    agent_trust = {"Version": "2012-10-17", "Statement": [{"Effect": "Allow",
        "Principal": {"Service": "bedrock-agentcore.amazonaws.com"}, "Action": "sts:AssumeRole"}]}
    create_role(f"{PREFIX}-agent-role", agent_trust)
    put_policy(f"{PREFIX}-agent-role", "AgentCorePolicy", {
        "Version": "2012-10-17",
        "Statement": [
            {"Sid": "SecretsAndConfig", "Effect": "Allow",
             "Action": ["secretsmanager:GetSecretValue", "ssm:GetParameter",
                        "ssm:GetParameters", "kms:Decrypt"], "Resource": "*"},
            {"Sid": "BedrockGateway", "Effect": "Allow",
             "Action": ["bedrock-agentcore:InvokeGateway"], "Resource": "*"},
            {"Sid": "BedrockAgentRuntime", "Effect": "Allow",
             "Action": ["bedrock-agentcore:InvokeAgentRuntime"],
             "Resource": f"arn:aws:bedrock-agentcore:{REGION}:{account_id}:runtime/*"},
            {"Sid": "BedrockPrompt", "Effect": "Allow",
             "Action": ["bedrock:GetPrompt"], "Resource": "*"},
            {"Sid": "BedrockGuardrail", "Effect": "Allow",
             "Action": ["bedrock:ApplyGuardrail"],
             "Resource": f"arn:aws:bedrock:{REGION}:{account_id}:guardrail/*"},
            {"Sid": "DynamoDB", "Effect": "Allow",
             "Action": ["dynamodb:PutItem", "dynamodb:GetItem", "dynamodb:UpdateItem",
                        "dynamodb:DeleteItem", "dynamodb:Scan", "dynamodb:Query",
                        "dynamodb:DescribeTable", "dynamodb:CreateTable"], "Resource": "*"},
            {"Sid": "ECRAuth",   "Effect": "Allow", "Action": ["ecr:GetAuthorizationToken"], "Resource": "*"},
            {"Sid": "ECRPull",   "Effect": "Allow",
             "Action": ["ecr:BatchGetImage", "ecr:GetDownloadUrlForLayer", "ecr:BatchCheckLayerAvailability"],
             "Resource": f"arn:aws:ecr:{REGION}:{account_id}:repository/*"},
            {"Sid": "CloudWatchLogs", "Effect": "Allow",
             "Action": ["logs:CreateLogGroup", "logs:CreateLogStream", "logs:PutLogEvents",
                        "logs:DescribeLogGroups", "logs:DescribeLogStreams"], "Resource": "*"},
            {"Sid": "XRayTracing", "Effect": "Allow",
             "Action": ["xray:PutTraceSegments", "xray:PutTelemetryRecords",
                        "xray:GetSamplingRules", "xray:GetSamplingTargets"], "Resource": "*"},
        ]
    })

    # ── ECS Execution Role — SSM + Secrets access ────────────────────────────
    # This role is created by Terraform for the ECS tasks (platform + UI).
    # It needs SSM and SecretsManager permissions to inject secrets at task startup.
    # Error seen: "not authorized to perform ssm:GetParameters on resource: .../platform_api_key"
    ecs_exec_role = f"{PREFIX}-ecs-execution"
    try:
        iam.get_role(RoleName=ecs_exec_role)
        put_policy(ecs_exec_role, "SSMSecretsAccess", {
            "Version": "2012-10-17",
            "Statement": [
                {
                    "Sid": "SSMParams",
                    "Effect": "Allow",
                    "Action": [
                        "ssm:GetParameter",
                        "ssm:GetParameters",
                        "ssm:GetParametersByPath",
                    ],
                    "Resource": f"arn:aws:ssm:{REGION}:{account_id}:parameter/*",
                },
                {
                    "Sid": "SecretsManager",
                    "Effect": "Allow",
                    "Action": ["secretsmanager:GetSecretValue"],
                    "Resource": "*",
                },
                {
                    "Sid": "KMSDecrypt",
                    "Effect": "Allow",
                    "Action": ["kms:Decrypt"],
                    "Resource": "*",
                },
            ]
        })
        ok(f"{ecs_exec_role} — SSM + Secrets policy applied")
    except ClientError:
        warn(f"{ecs_exec_role} not found — will be created by Terraform, run: python deploy.py iam  after terraform apply")

    for role_suffix in ["lambda-mcp", "gateway-role", "agent-role"]:
        track("iam-role", f"{PREFIX}-{role_suffix}",
              f"arn:aws:iam::{account_id}:role/{PREFIX}-{role_suffix}")
    ok("IAM done")


def step_guardrails():
    header("Step 2b: Bedrock Guardrail")
    bedrock = c("bedrock")
    ssm     = c("ssm")
    name    = f"{PREFIX}-guardrail"

    existing_id = None
    try:
        v = ssm.get_parameter(Name=f"{SSM_PREFIX}/bedrock/guardrail_id")["Parameter"]["Value"]
        if v and v != "CHANGE_ME":
            existing_id = v
    except ClientError:
        pass

    # ── Policy definitions — shared by both create and update paths ──────────
    topic_policy = {
        "topicsConfig": [
            {
                # OffTopicQuery — blocks clearly non-medical queries.
                # Definition enumerates concrete denied domains (NOT abstract "unrelated to X")
                # Previous failure: "unrelated to clinical trials" caused the Bedrock classifier
                # to block mRNA-1273, COVID vaccines, cancer trials. Fix: enumerate obviously
                # non-medical domains so the classifier draws the boundary correctly.
                "name": "OffTopicQuery",
                "definition": (
                    "Personal entertainment, sports, weather, financial markets, "
                    "creative writing, software development, or any topic that has "
                    "no connection to medicine, biology, or drug research."
                ),
                "examples": [
                    "Tell me a joke.",
                    "What is the weather forecast for New York?",
                    "Help me write a cover letter for a job application.",
                ],
                "type": "DENY",
            },
            {
                "name": "PersonalMedicalAdvice",
                "definition": "Direct medical advice, dosage instructions, or recommendations to start, stop, or change medication for an individual patient.",
                "examples": [
                    "Take 500mg of metformin daily.",
                    "Stop your medication before the trial.",
                    "I recommend enrolling based on your symptoms.",
                ],
                "type": "DENY",
            },
        ]
    }
    content_policy = {
        "filtersConfig": [
            {"type": "HATE",          "inputStrength": "HIGH", "outputStrength": "HIGH"},
            {"type": "INSULTS",       "inputStrength": "HIGH", "outputStrength": "HIGH"},
            {"type": "SEXUAL",        "inputStrength": "HIGH", "outputStrength": "HIGH"},
            {"type": "VIOLENCE",      "inputStrength": "HIGH", "outputStrength": "HIGH"},
            {"type": "MISCONDUCT",    "inputStrength": "HIGH", "outputStrength": "HIGH"},
            {"type": "PROMPT_ATTACK", "inputStrength": "HIGH", "outputStrength": "NONE"},
        ]
    }
    pii_policy = {
        "piiEntitiesConfig": [
            {"type": "NAME",                     "action": "ANONYMIZE"},
            {"type": "EMAIL",                    "action": "ANONYMIZE"},
            {"type": "PHONE",                    "action": "ANONYMIZE"},
            {"type": "US_SOCIAL_SECURITY_NUMBER","action": "BLOCK"},
            # AGE removed — false positive: "participants aged 18 and older" → "18" matched as AGE
            # ADDRESS removed — false positive: "in the US" → "US" matched as ADDRESS
            # Both caused ANONYMIZED interventions that blocked legitimate clinical trial responses
        ]
    }
    # Contextual grounding removed — architecturally wrong at supervisor level.
    # The supervisor synthesises across sub-agent responses (which are themselves
    # summaries of raw tool results). Two paraphrasing layers cause legitimate
    # answers to score below any reasonable threshold, blocking valid responses.
    # Grounded retrieval is enforced at sub-agent level. The supervisor guardrail
    # checks content filters and denied topics only.
    grounding_policy = None
    blocked_input_msg = (
        "Your request could not be processed. It either contains prohibited content "
        "or is outside the scope of this clinical trial research platform. "
        "Please ask a question related to clinical trials or pharmaceutical research."
    )
    blocked_output_msg = (
        "This response was blocked by the content safety guardrail. "
        "Please consult a qualified healthcare professional for personal medical advice."
    )

    if existing_id:
        info(f"Guardrail exists ({existing_id}) — updating content then creating new version...")
        try:
            # Update guardrail content first — same as prompts pattern.
            # Without this, create_guardrail_version just re-versions the OLD config.
            bedrock.update_guardrail(
                guardrailIdentifier  = existing_id,
                name                 = f"{PREFIX}-guardrail",
                description          = "VS AgentCore clinical trial research platform — input + output guardrail",
                topicPolicyConfig    = topic_policy,
                contentPolicyConfig  = content_policy,
                sensitiveInformationPolicyConfig = pii_policy,
                blockedInputMessaging   = blocked_input_msg,
                blockedOutputsMessaging = blocked_output_msg,
            )
            info(f"Guardrail content updated")
            ver_resp     = bedrock.create_guardrail_version(guardrailIdentifier=existing_id,
                                                             description="Updated by deploy.py")
            guardrail_id = existing_id
            gver         = str(ver_resp["version"])
            ok(f"New version: {gver}")
        except Exception as e:
            warn(f"Could not update guardrail: {e}")
            guardrail_id = existing_id
            gver = ssm.get_parameter(Name=f"{SSM_PREFIX}/bedrock/guardrail_version")["Parameter"]["Value"]
    else:
        info(f"Creating guardrail: {name}")
        resp = bedrock.create_guardrail(
            name        = name,
            description = "VS AgentCore clinical trial research platform — input + output guardrail",
            topicPolicyConfig                = topic_policy,
            contentPolicyConfig              = content_policy,
            sensitiveInformationPolicyConfig = pii_policy,
            blockedInputMessaging            = blocked_input_msg,
            blockedOutputsMessaging          = blocked_output_msg,
        )
        guardrail_id = resp["guardrailId"]
        info(f"Created: {guardrail_id}  ARN: {resp['guardrailArn']}")
        v_resp = bedrock.create_guardrail_version(guardrailIdentifier=guardrail_id,
                                                   description="Initial version — deploy.py")
        gver = str(v_resp["version"])

    ssm.put_parameter(Name=f"{SSM_PREFIX}/bedrock/guardrail_id",      Value=guardrail_id, Type="String", Overwrite=True)
    ssm.put_parameter(Name=f"{SSM_PREFIX}/bedrock/guardrail_version",  Value=gver,         Type="String", Overwrite=True)
    ok(f"SSM: {SSM_PREFIX}/bedrock/guardrail_id = {guardrail_id}")
    ok(f"SSM: {SSM_PREFIX}/bedrock/guardrail_version = {gver}")
    track("bedrock-guardrail", name, guardrail_id)
    ok("Guardrail done")


def step_lambdas():
    header("Step 3: Lambda MCP Tools")
    account_id = get_account_id()
    ecr_base   = ecr_login(account_id)
    lam        = c("lambda")
    lambda_role = f"arn:aws:iam::{account_id}:role/{PREFIX}-lambda-mcp"

    for tool in ["search", "graph", "hitl", "summariser", "chart"]:
        print(f"\n  \u2500\u2500 {tool}_lambda")
        repo = ensure_ecr_repo(account_id, f"{tool}-tool")
        tag  = f"{repo}:latest"
        func = f"{PREFIX}-{tool}-tool"
        src  = ROOT / "mcp_tools" / f"{tool}_lambda"

        run(["docker", "buildx", "build",
             "--platform", "linux/amd64",
             "--output",   "type=registry",
             "--provenance=false",
             "--no-cache",
             "-t", tag, str(src)])

        env_vars = {"Variables": {"SSM_PREFIX": SSM_PREFIX}}
        try:
            lam.get_function(FunctionName=func)
            info(f"Updating {func}...")
            lam.update_function_code(FunctionName=func, ImageUri=tag)
        except ClientError:
            info(f"Creating {func}...")
            try:
                lam.create_function(
                    FunctionName  = func,
                    PackageType   = "Image",
                    Code          = {"ImageUri": tag},
                    Role          = lambda_role,
                    Architectures = ["x86_64"],
                    Timeout       = 30,
                    MemorySize    = 512,
                    ImageConfig   = {"Command": ["handler.handler"]},
                    Environment   = env_vars,
                )
            except ClientError as e:
                warn(f"Create failed: {e}")
                continue

        wait_lambda(func)
        try:
            lam.get_waiter("function_updated").wait(FunctionName=func)
        except Exception:
            pass
        ok(func)
        track("lambda",   func,               f"arn:aws:lambda:{REGION}:{account_id}:function:{func}")
        track("ecr-repo", f"{PREFIX}/{tool}-tool", f"{ecr_base}/{PREFIX}/{tool}-tool")

    ok("Lambdas done")


def step_gateway():
    header("Step 4: MCP Gateway + Targets")
    account_id  = get_account_id()
    agc         = c("bedrock-agentcore-control")
    ssm         = c("ssm")
    lam         = c("lambda")
    iam         = c("iam")
    gateway_role = f"arn:aws:iam::{account_id}:role/{PREFIX}-gateway-role"

    # Find or create gateway
    gateway_id = gateway_url = None

    pages = agc.get_paginator("list_gateways").paginate() if hasattr(agc, "get_paginator") else [agc.list_gateways()]
    for page in agc.list_gateways().get("items", []) if True else []:
        pass
    gateways = agc.list_gateways().get("items", [])
    for gw in gateways:
        if gw["name"] == GATEWAY_NAME:
            gateway_id  = gw["gatewayId"]
            gateway_url = agc.get_gateway(gatewayIdentifier=gateway_id)["gatewayUrl"]
            info(f"Found existing gateway: {GATEWAY_NAME} ({gateway_id})")
            break

    if not gateway_id:
        for gw in gateways:
            if gw["name"] == "vs-agentcore-mcp":
                gateway_id  = gw["gatewayId"]
                gateway_url = agc.get_gateway(gatewayIdentifier=gateway_id)["gatewayUrl"]
                info(f"Reusing single-agent gateway ({gateway_id})")
                break

    if not gateway_id:
        info(f"Creating gateway: {GATEWAY_NAME}...")
        resp        = agc.create_gateway(
            name                 = GATEWAY_NAME,
            authorizerType       = "AWS_IAM",
            protocolType         = "MCP",
            roleArn              = gateway_role,
            protocolConfiguration= {"mcp": {"supportedVersions": ["2025-03-26"],
                                             "instructions": "VS AgentCore Multi-Agent MCP Gateway"}},
        )
        gateway_id  = resp["gatewayId"]
        gateway_url = resp["gatewayUrl"]
        print("  Waiting for ACTIVE", end="", flush=True)
        for _ in range(24):
            s = agc.get_gateway(gatewayIdentifier=gateway_id).get("status")
            if s == "ACTIVE":
                print(" \u2705")
                break
            print(".", end="", flush=True)
            time.sleep(5)

    info(f"Gateway ID:  {gateway_id}")
    info(f"Gateway URL: {gateway_url}")

    # Register/update targets
    def upsert_target(tgt_name, tool_name, tool_desc, lambda_func, schema):
        existing = next(
            (t["targetId"] for t in agc.list_gateway_targets(gatewayIdentifier=gateway_id).get("items", [])
             if t["name"] == tgt_name), None
        )
        lambda_arn = f"arn:aws:lambda:{REGION}:{account_id}:function:{lambda_func}"
        target_cfg = {"mcp": {"lambda": {"lambdaArn": lambda_arn,
            "toolSchema": {"inlinePayload": [{"name": tool_name, "description": tool_desc,
                                              "inputSchema": schema}]}}}}
        cred_cfg   = [{"credentialProviderType": "GATEWAY_IAM_ROLE"}]
        if existing:
            info(f"Updating {tgt_name}...")
            agc.update_gateway_target(gatewayIdentifier=gateway_id, targetId=existing,
                                       name=tgt_name, description=tool_desc,
                                       targetConfiguration=target_cfg,
                                       credentialProviderConfigurations=cred_cfg)
        else:
            info(f"Creating {tgt_name}...")
            agc.create_gateway_target(gatewayIdentifier=gateway_id, name=tgt_name,
                                       description=tool_desc, targetConfiguration=target_cfg,
                                       credentialProviderConfigurations=cred_cfg)
        ok(tgt_name)

    upsert_target("tool-search",    "search_tool",     "Semantic search over clinical trial chunks in Pinecone.",                     f"{PREFIX}-search-tool",     {"type": "object", "properties": {"query": {"type": "string"}, "top_k": {"type": "integer"}}, "required": ["query"]})
    upsert_target("tool-graph",     "graph_tool",      "Cypher query on Neo4j biomedical graph. Read-only.",                          f"{PREFIX}-graph-tool",      {"type": "object", "properties": {"cypher": {"type": "string"}}, "required": ["cypher"]})
    upsert_target("tool-summariser","summariser_tool", "Synthesise chunks into one cited answer with NCT ID citations.",               f"{PREFIX}-summariser-tool", {"type": "object", "properties": {"chunks": {"type": "array", "items": {"type": "string"}}, "query": {"type": "string"}}, "required": ["chunks"]})
    upsert_target("tool-chart",     "chart_tool",      "Generate Chart.js config from numerical clinical trial data.",                 f"{PREFIX}-chart-tool",      {"type": "object", "properties": {"data": {"type": "string"}, "chart_type": {"type": "string"}, "title": {"type": "string"}}, "required": ["data"]})

    # Detect clarify target name
    existing_targets = agc.list_gateway_targets(gatewayIdentifier=gateway_id).get("items", [])
    clarify_name = next((t["name"] for t in existing_targets if t["name"] in ("clarify", "tool-hitl")), "clarify")
    upsert_target(clarify_name, "ask_user_input",
                  "Ask user to clarify an ambiguous query. Options must be real trial names.",
                  f"{PREFIX}-hitl-tool",
                  {"type": "object", "properties": {"question": {"type": "string"},
                   "options": {"type": "array", "items": {"type": "string"}},
                   "allow_freetext": {"type": "boolean"},
                   "user_answer": {"type": "string"}}, "required": []})

    # Lambda resource-based permissions
    info("Adding Lambda invoke permissions for gateway role...")
    for tool in ["search", "graph", "hitl", "summariser", "chart"]:
        func = f"{PREFIX}-{tool}-tool"
        stmt = f"AllowGatewayInvoke-{func}"
        try:
            lam.remove_permission(FunctionName=func, StatementId=stmt)
        except ClientError:
            pass
        try:
            lam.add_permission(FunctionName=func, StatementId=stmt,
                               Action="lambda:InvokeFunction",
                               Principal="bedrock-agentcore.amazonaws.com")
            ok(f"Lambda permission: {func}")
        except ClientError as e:
            warn(f"Lambda permission failed {func}: {e}")

    # Update gateway role policy
    gw_role_arn  = agc.get_gateway(gatewayIdentifier=gateway_id).get("roleArn", "")
    gw_role_name = gw_role_arn.split("/")[-1] if gw_role_arn else ""
    if gw_role_name:
        lambda_arns = [
            f"arn:aws:lambda:{REGION}:{account_id}:function:vs-agentcore-{t}-tool"
            for t in ["search", "graph", "hitl", "summariser"]
        ] + [
            f"arn:aws:lambda:{REGION}:{account_id}:function:{PREFIX}-{t}-tool"
            for t in ["search", "graph", "hitl", "summariser", "chart"]
        ]
        try:
            iam.put_role_policy(
                RoleName   = gw_role_name,
                PolicyName = "GatewayPolicyMultiAgent",
                PolicyDocument = json.dumps({
                    "Version": "2012-10-17",
                    "Statement": [
                        {"Sid": "InvokeLambdaTools", "Effect": "Allow",
                         "Action": ["lambda:InvokeFunction"], "Resource": lambda_arns},
                        {"Sid": "CloudWatchLogs", "Effect": "Allow",
                         "Action": ["logs:CreateLogGroup", "logs:CreateLogStream",
                                    "logs:PutLogEvents", "logs:DescribeLogGroups",
                                    "logs:DescribeLogStreams"], "Resource": "*"},
                    ]
                })
            )
            ok(f"Gateway role policy updated: {gw_role_name}")
        except ClientError as e:
            warn(f"Gateway role policy update failed: {e}")

    ssm.put_parameter(Name=f"{SSM_PREFIX}/mcp/gateway_url", Value=gateway_url,
                      Type="String", Overwrite=True)
    ok(f"SSM: {SSM_PREFIX}/mcp/gateway_url")
    track("mcp-gateway", GATEWAY_NAME, gateway_id)
    ok(f"Gateway done  URL: {gateway_url}")


def step_platform():
    header("Step 5: Platform + UI (Terraform / ECS Fargate)")
    account_id = get_account_id()
    ecr_base   = ecr_login(account_id)
    infra_dir  = ROOT / "infra"

    for name, src_dir in [("platform", ROOT / "platform"), ("ui", ROOT / "ui")]:
        repo = ensure_ecr_repo(account_id, name)
        tag  = f"{repo}:latest"
        run(["docker", "buildx", "build", "--platform", "linux/amd64",
             "--output", "type=registry", "--provenance=false", "--no-cache",
             "-t", tag, str(src_dir)])
        info(f"{name} image pushed: {tag}")

    platform_tag = f"{account_id}.dkr.ecr.{REGION}.amazonaws.com/{PREFIX}/platform:latest"
    ui_tag       = f"{account_id}.dkr.ecr.{REGION}.amazonaws.com/{PREFIX}/ui:latest"

    rds_pwd = os.environ.get("RDS_PASSWORD", "")
    if not rds_pwd:
        fail("RDS_PASSWORD not set in environment")
        sys.exit(1)

    tf_env = {**os.environ, "TF_VAR_postgres_password": rds_pwd}

    try:
        c("s3").create_bucket(Bucket=f"{PREFIX}-tfstate",
                               CreateBucketConfiguration={"LocationConstraint": REGION}
                               if REGION != "us-east-1" else {})
    except ClientError:
        pass  # bucket exists

    run(["terraform", "init", "-upgrade", "-input=false"], cwd=infra_dir)
    tf_vars = [f"-var=platform_image_uri={platform_tag}",
               f"-var=ui_image_uri={ui_tag}",
               f"-var=aws_region={REGION}"]

    action = sys.argv[1] if len(sys.argv) > 1 else ""
    if action == "plan":
        run(["terraform", "plan"]   + tf_vars, cwd=infra_dir, extra_env=tf_env)
    else:
        run(["terraform", "apply", "-auto-approve", "-input=false"] + tf_vars,
            cwd=infra_dir, extra_env=tf_env)

        # ── Post-terraform: force ECS services to use the latest task definition ──
        # Terraform creates a new task definition revision but the ECS service
        # may still be running an old revision. Force-update both services so
        # students always get the correct AGENT_API_URL and image on first deploy.
        ecs = c("ecs")
        for svc, td in [("platform", "platform"), ("ui", "ui")]:
            svc_name = f"{PREFIX}-{svc}"
            td_name  = f"{PREFIX}-{td}"
            try:
                # Get latest task definition revision
                td_desc = c("ecs").describe_task_definition(taskDefinition=td_name)
                latest_td_arn = td_desc["taskDefinition"]["taskDefinitionArn"]
                ecs.update_service(
                    cluster        = f"{PREFIX}-cluster",
                    service        = svc_name,
                    taskDefinition = latest_td_arn,
                    forceNewDeployment = True,
                )
                ok(f"{svc_name} → {latest_td_arn.split('/')[-1]}")
            except Exception as e:
                warn(f"{svc_name} update failed: {e}")

        # ── Restore ALB idle timeout (terraform resets it to 60s) ────────────────
        try:
            alb_arn = c("elbv2").describe_load_balancers(
                Names=[f"{PREFIX}-alb"]
            )["LoadBalancers"][0]["LoadBalancerArn"]
            c("elbv2").modify_load_balancer_attributes(
                LoadBalancerArn = alb_arn,
                Attributes      = [{"Key": "idle_timeout.timeout_seconds", "Value": "300"}],
            )
            ok("ALB idle timeout = 300s")
        except Exception as e:
            warn(f"ALB timeout update failed: {e}")

        print()
        ok("Platform done")
        print("  \u26a0\ufe0f  MANUAL STEP: set POSTGRES_URL in .env then re-run: python deploy.py secrets")


def step_agents(only=None):
    header("Step 6: AgentCore Runtimes")
    account_id = get_account_id()
    ecr_base   = ecr_login(account_id)
    agc        = c("bedrock-agentcore-control")
    ssm        = c("ssm")
    agent_role = f"arn:aws:iam::{account_id}:role/{PREFIX}-agent-role"

    def build_and_push(agent):
        repo = ensure_ecr_repo(account_id, f"agent-{agent}")
        tag  = f"{repo}:latest"
        info(f"Building {agent} (linux/arm64)...")
        run(["docker", "buildx", "build",
             "--platform", "linux/arm64",
             "--output",   "type=registry",
             "--provenance=false",
             "--no-cache",
             "-t", tag,
             "--file", str(ROOT / "agents" / agent / "Dockerfile"),
             str(ROOT)])
        ok(f"Pushed: {tag}")
        return tag

    def deploy_runtime(agent_name, description, image_tag):
        runtime_name = f"{PREFIX.replace('-','_')}_{agent_name.replace('-','_')}"
        log_group    = f"/agentcore/{PREFIX}/{agent_name}-agent"
        env_vars     = {
            "SSM_PREFIX":          SSM_PREFIX,
            "AWS_REGION":          REGION,
            "AWS_DEFAULT_REGION":  REGION,
            "AGENT_ENV":           "prod",
            "AGENT_NAME":          agent_name,  # no -agent suffix — Dockerfile uses: python -m agents.${AGENT_NAME}.app
            "LOG_GROUP_NAME":      log_group,
        }
        artifact = {"containerConfiguration": {"containerUri": image_tag}}
        network  = {"networkMode": "PUBLIC"}

        existing = next(
            (r["agentRuntimeArn"] for r in agc.list_agent_runtimes().get("agentRuntimes", [])
             if r["agentRuntimeName"] == runtime_name), None
        )

        if existing:
            runtime_id = existing.split("runtime/")[-1]
            info(f"Runtime exists — updating {agent_name}...")
            agc.update_agent_runtime(agentRuntimeId=runtime_id, roleArn=agent_role,
                                      networkConfiguration=network,
                                      agentRuntimeArtifact=artifact,
                                      environmentVariables=env_vars)
            runtime_arn = existing
        else:
            info(f"Creating runtime: {runtime_name}...")
            resp        = agc.create_agent_runtime(
                agentRuntimeName      = runtime_name,
                description           = description,
                roleArn               = agent_role,
                agentRuntimeArtifact  = artifact,
                networkConfiguration  = network,
                environmentVariables  = env_vars,
            )
            runtime_arn = resp["agentRuntimeArn"]
            runtime_id  = runtime_arn.split("runtime/")[-1]

        wait_runtime(runtime_id)
        info(f"ARN: {runtime_arn}")

        ssm.put_parameter(Name=f"{SSM_PREFIX}/agents/{agent_name}/runtime_arn",
                          Value=runtime_arn, Type="String", Overwrite=True)
        ok(f"SSM: {SSM_PREFIX}/agents/{agent_name}/runtime_arn")
        track("agentcore-runtime", f"{agent_name}-agent", runtime_arn)

    descriptions = {
        "research":  "Research Agent — Pinecone semantic search + GPT-4o synthesis",
        "knowledge": "Knowledge Agent — Neo4j Cypher queries",
        "safety":    "Safety Agent — faithfulness + consistency evaluation",
        "chart":     "Chart Agent — Chart.js generation from trial data",
        "supervisor":"Supervisor Agent — A2A routing + full middleware stack",
    }

    if only:
        info(f"Deploying only: {only}")

    agents_to_deploy = [a for a in SUB_AGENTS if not only or a == only]
    for agent in agents_to_deploy:
        print(f"\n  \u2500\u2500 {agent}")
        try:
            tag = build_and_push(agent)
            deploy_runtime(agent, descriptions[agent], tag)
        except Exception as e:
            warn(f"{agent} failed: {e} — continuing")

    if not only or only == "supervisor":
        print(f"\n  \u2500\u2500 supervisor (last — reads sub-agent ARNs from SSM)")
        try:
            tag = build_and_push("supervisor")
            deploy_runtime("supervisor", descriptions["supervisor"], tag)
        except Exception as e:
            fail(f"Supervisor deployment failed: {e}")
            sys.exit(1)

    for agent in AGENTS:
        track("ecr-repo", f"{PREFIX}/agent-{agent}",
              f"{account_id}.dkr.ecr.{REGION}.amazonaws.com/{PREFIX}/agent-{agent}")
    ok("Agents done")


def step_ssm_arns():
    header("Step 7: Verify sub-agent ARNs in SSM")
    ssm = c("ssm")
    for agent in SUB_AGENTS:
        try:
            arn = ssm.get_parameter(Name=f"{SSM_PREFIX}/agents/{agent}/runtime_arn")["Parameter"]["Value"]
            info(f"{agent}: {arn}")
        except ClientError:
            warn(f"{agent}: NOT SET")
    info("Supervisor reads these at cold start via a2a_tools._get_runtime_arns()")


def step_registry():
    header("Step 7b: Agent Registry \u2192 SSM")
    ssm = c("ssm")

    registry = [
        {
            "name": "research",
            "description": (
                "Retrieves evidence from clinical trial protocol documents via Pinecone semantic search. "
                "Use for: efficacy results, adverse events, safety profiles, dosage and administration, "
                "study procedures, and primary or secondary endpoint details. "
                "Returns cited prose with NCT ID citations. "
                "Do NOT use for structured queries about which trials exist, enrollment counts, "
                "sponsors, sites, or eligibility criteria text — use knowledge agent for those."
            ),
            "port": 8001
        },
        {
            "name": "knowledge",
            "description": (
                "Queries the Neo4j biomedical knowledge graph with Cypher. "
                "Use for: which trials exist for a disease, trial phase and status, enrollment counts, "
                "sponsors, CROs, trial sites and countries, outcome measure definitions, "
                "patient eligibility criteria text, and MeSH term associations. "
                "Returns structured records — trial names, NCT IDs, and metadata only. "
                "Does NOT contain efficacy percentages, hazard ratios, p-values, adverse event rates, "
                "dosage data, or any numerical outcome statistics — use research agent for those."
            ),
            "port": 8002
        },
        {
            "name": "chart",
            "description": (
                "Generates Chart.js visualisations from numerical clinical trial data. "
                "Call AFTER research or knowledge agent has retrieved the numbers. "
                "Use when the user asks for a chart, graph, or visual comparison, "
                "or when the answer contains comparative numerical data across trials. "
                "Pass the retrieved numbers as input — do not call without data from a prior agent."
            ),
            "port": 8005
        },
    ]
    # NOTE: safety agent intentionally excluded from registry.
    # OutputGuardrailMiddleware handles output safety via Bedrock Guardrails.
    # The safety agent container is still deployed but the Supervisor never routes to it.

    ssm.put_parameter(Name=f"{SSM_PREFIX}/agents/registry",
                      Value=json.dumps(registry), Type="String", Overwrite=True)
    ok(f"Registry written: {SSM_PREFIX}/agents/registry")
    info(f"Agents: {[a['name'] for a in registry]}")


def step_redeploy(target="both"):
    header(f"Quick ECS redeploy — {target}")
    ecs = c("ecs")
    if target in ("platform", "both"):
        ecs.update_service(cluster=f"{PREFIX}-cluster", service=f"{PREFIX}-platform",
                           forceNewDeployment=True)
        ok(f"{PREFIX}-platform redeploy triggered")
    if target in ("ui", "both"):
        ecs.update_service(cluster=f"{PREFIX}-cluster", service=f"{PREFIX}-ui",
                           forceNewDeployment=True)
        ok(f"{PREFIX}-ui redeploy triggered")


def step_all():
    step_prompts()
    step_secrets()
    step_iam()
    step_guardrails()
    step_lambdas()
    step_gateway()
    step_platform()
    print()
    sep()
    print("  \u26a0\ufe0f  MANUAL STEP REQUIRED before deploying agents:")
    print()
    print("  1. Set POSTGRES_URL in your environment:")
    print("     POSTGRES_URL=postgresql://postgres:<pwd>@<rds-endpoint>/clinical_agent")
    print("  2. Re-run secrets:  python deploy.py secrets")
    print("  3. Deploy agents:   python deploy.py agents")
    print("  4. Write registry:  python deploy.py registry")
    sep()


def step_destroy():
    header("Destroy Terraform resources")
    infra_dir = ROOT / "infra"
    run(["terraform", "destroy", "-auto-approve",
         "-var=platform_image_uri=placeholder",
         "-var=ui_image_uri=placeholder",
         f"-var=aws_region={REGION}"],
        cwd=infra_dir)


# ── CLI dispatch ──────────────────────────────────────────────────────────

USAGE = """
Usage: python deploy.py <command>

Commands:
  check       Verify secrets, prompts, guardrail, gateway, lambdas, RDS, IAM
  prompts     Create Bedrock prompts (one per agent) → SSM
  secrets     Push API keys and SSM parameters
  iam         Create IAM roles and policies
  guardrails  Create Bedrock Guardrail (denied topics, content filters, PII) → SSM
  lambdas     Build and deploy Lambda MCP tools
  gateway     Create/update MCP Gateway and targets
  platform    Deploy ECS platform + UI via Terraform
  agents      Build and deploy AgentCore Runtimes
  ssm-arns    Verify sub-agent ARNs in SSM
  registry    Write agent registry to SSM
  redeploy    Quick ECS redeploy  [platform|ui|both]
  all         Run all steps in order (pauses before agents)
  destroy     Destroy Terraform resources
"""

def main():
    if len(sys.argv) < 2:
        print(USAGE)
        sys.exit(1)

    cmd = sys.argv[1].lower()

    if cmd != "check":
        check_prereqs()

    account_id = get_account_id()
    ecr_base   = f"{account_id}.dkr.ecr.{REGION}.amazonaws.com"

    print("=" * 50)
    print(f"VS AgentCore Multi-Agent — {cmd.upper()}")
    print(f"Account: {account_id}  Region: {REGION}")
    print(f"Root:    {ROOT}")
    print("=" * 50)

    dispatch = {
        "check":      step_check,
        "prompts":    step_prompts,
        "secrets":    step_secrets,
        "iam":        step_iam,
        "guardrails": step_guardrails,
        "lambdas":    step_lambdas,
        "gateway":    step_gateway,
        "platform":   step_platform,
        "plan":       step_platform,
        "agents":     lambda: step_agents(only=next((sys.argv[i+1] for i,a in enumerate(sys.argv) if a=="--agent" and i+1<len(sys.argv)), None)),
        "ssm-arns":   step_ssm_arns,
        "registry":   step_registry,
        "all":        step_all,
        "destroy":    step_destroy,
        "redeploy":   lambda: step_redeploy(sys.argv[2] if len(sys.argv) > 2 else "both"),
    }

    fn = dispatch.get(cmd)
    if not fn:
        print(f"Unknown command: {cmd}")
        print(USAGE)
        sys.exit(1)

    try:
        fn()
    except KeyboardInterrupt:
        print("\n\u26a0\ufe0f  Interrupted")
        sys.exit(1)
    except Exception as e:
        fail(f"Step failed: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()